//# DO NOT MODIFY.
//# This is autogenerated by `ySwiftCodeUpdater`(https://github.com/YOCKOW/ySwiftCodeUpdater).
//# Please see documents in this project to learn how to regenerate.
//# The material(s) to generate this file was/were obtained from below:
//
// URL: https://raw.githubusercontent.com/apple/swift-corelibs-foundation/master/CoreFoundation/String.subproj/CFString.h
// ETag: W/"83e5d78bb3bb36d5a6d60f112e9fe1028f840b3496fa21b1f34841345fc8f74f"
//
// URL: https://raw.githubusercontent.com/apple/swift-corelibs-foundation/master/CoreFoundation/String.subproj/CFStringEncodingExt.h
// ETag: W/"4ba9e6ff74a97d02ff591804522d7648b0f0b19040d689365c7fbed4b1ad0ff3"

import CoreFoundation

/*
  CFString.h
  Copyright (c) 1998-2019, Apple Inc. and the Swift project authors
  
  Portions Copyright (c) 2014-2019, Apple Inc. and the Swift project authors
  Licensed under Apache License v2.0 with Runtime Library Exception
  See http://swift.org/LICENSE.txt for license information
  See http://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
  
*/
extension CFString.Encoding {
  public static let macRoman = CFString.Encoding(rawValue: 0x0)
  public static let unicode = CFString.Encoding(rawValue: 0x100)
  public static let utf16 = CFString.Encoding(rawValue: 0x100)
  public static let isoLatin1 = CFString.Encoding(rawValue: 0x201)
  public static let windowsLatin1 = CFString.Encoding(rawValue: 0x500)
  public static let ascii = CFString.Encoding(rawValue: 0x600)
  public static let nextStepLatin = CFString.Encoding(rawValue: 0xB01)
  public static let nonLossyASCII = CFString.Encoding(rawValue: 0xBFF)
  public static let utf8 = CFString.Encoding(rawValue: 0x8000100)
  public static let utf32 = CFString.Encoding(rawValue: 0xC000100)
  public static let utf16be = CFString.Encoding(rawValue: 0x10000100)
  public static let utf16le = CFString.Encoding(rawValue: 0x14000100)
  public static let utf32be = CFString.Encoding(rawValue: 0x18000100)
  public static let utf32le = CFString.Encoding(rawValue: 0x1C000100)
}

/*
  CFStringEncodingExt.h
  Copyright (c) 1998-2019, Apple Inc. and the Swift project authors
  
  Portions Copyright (c) 2014-2019, Apple Inc. and the Swift project authors
  Licensed under Apache License v2.0 with Runtime Library Exception
  See http://swift.org/LICENSE.txt for license information
  See http://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
  
*/
extension CFString.Encoding {
  public static let macJapanese = CFString.Encoding(rawValue: 0x1)
  public static let macChineseTrad = CFString.Encoding(rawValue: 0x2)
  public static let macKorean = CFString.Encoding(rawValue: 0x3)
  public static let macArabic = CFString.Encoding(rawValue: 0x4)
  public static let macHebrew = CFString.Encoding(rawValue: 0x5)
  public static let macGreek = CFString.Encoding(rawValue: 0x6)
  public static let macCyrillic = CFString.Encoding(rawValue: 0x7)
  public static let macDevanagari = CFString.Encoding(rawValue: 0x9)
  public static let macGurmukhi = CFString.Encoding(rawValue: 0xA)
  public static let macGujarati = CFString.Encoding(rawValue: 0xB)
  public static let macOriya = CFString.Encoding(rawValue: 0xC)
  public static let macBengali = CFString.Encoding(rawValue: 0xD)
  public static let macTamil = CFString.Encoding(rawValue: 0xE)
  public static let macTelugu = CFString.Encoding(rawValue: 0xF)
  public static let macKannada = CFString.Encoding(rawValue: 0x10)
  public static let macMalayalam = CFString.Encoding(rawValue: 0x11)
  public static let macSinhalese = CFString.Encoding(rawValue: 0x12)
  public static let macBurmese = CFString.Encoding(rawValue: 0x13)
  public static let macKhmer = CFString.Encoding(rawValue: 0x14)
  public static let macThai = CFString.Encoding(rawValue: 0x15)
  public static let macLaotian = CFString.Encoding(rawValue: 0x16)
  public static let macGeorgian = CFString.Encoding(rawValue: 0x17)
  public static let macArmenian = CFString.Encoding(rawValue: 0x18)
  public static let macChineseSimp = CFString.Encoding(rawValue: 0x19)
  public static let macTibetan = CFString.Encoding(rawValue: 0x1A)
  public static let macMongolian = CFString.Encoding(rawValue: 0x1B)
  public static let macEthiopic = CFString.Encoding(rawValue: 0x1C)
  public static let macCentralEurRoman = CFString.Encoding(rawValue: 0x1D)
  public static let macVietnamese = CFString.Encoding(rawValue: 0x1E)
  public static let macExtArabic = CFString.Encoding(rawValue: 0x1F)
  public static let macSymbol = CFString.Encoding(rawValue: 0x21)
  public static let macDingbats = CFString.Encoding(rawValue: 0x22)
  public static let macTurkish = CFString.Encoding(rawValue: 0x23)
  public static let macCroatian = CFString.Encoding(rawValue: 0x24)
  public static let macIcelandic = CFString.Encoding(rawValue: 0x25)
  public static let macRomanian = CFString.Encoding(rawValue: 0x26)
  public static let macCeltic = CFString.Encoding(rawValue: 0x27)
  public static let macGaelic = CFString.Encoding(rawValue: 0x28)
  public static let macFarsi = CFString.Encoding(rawValue: 0x8C)
  public static let macUkrainian = CFString.Encoding(rawValue: 0x98)
  public static let macInuit = CFString.Encoding(rawValue: 0xEC)
  public static let macVT100 = CFString.Encoding(rawValue: 0xFC)
  public static let macHFS = CFString.Encoding(rawValue: 0xFF)
  public static let isoLatin2 = CFString.Encoding(rawValue: 0x202)
  public static let isoLatin3 = CFString.Encoding(rawValue: 0x203)
  public static let isoLatin4 = CFString.Encoding(rawValue: 0x204)
  public static let isoLatinCyrillic = CFString.Encoding(rawValue: 0x205)
  public static let isoLatinArabic = CFString.Encoding(rawValue: 0x206)
  public static let isoLatinGreek = CFString.Encoding(rawValue: 0x207)
  public static let isoLatinHebrew = CFString.Encoding(rawValue: 0x208)
  public static let isoLatin5 = CFString.Encoding(rawValue: 0x209)
  public static let isoLatin6 = CFString.Encoding(rawValue: 0x20A)
  public static let isoLatinThai = CFString.Encoding(rawValue: 0x20B)
  public static let isoLatin7 = CFString.Encoding(rawValue: 0x20D)
  public static let isoLatin8 = CFString.Encoding(rawValue: 0x20E)
  public static let isoLatin9 = CFString.Encoding(rawValue: 0x20F)
  public static let isoLatin10 = CFString.Encoding(rawValue: 0x210)
  public static let dosLatinUS = CFString.Encoding(rawValue: 0x400)
  public static let dosGreek = CFString.Encoding(rawValue: 0x405)
  public static let dosBalticRim = CFString.Encoding(rawValue: 0x406)
  public static let dosLatin1 = CFString.Encoding(rawValue: 0x410)
  public static let dosGreek1 = CFString.Encoding(rawValue: 0x411)
  public static let dosLatin2 = CFString.Encoding(rawValue: 0x412)
  public static let dosCyrillic = CFString.Encoding(rawValue: 0x413)
  public static let dosTurkish = CFString.Encoding(rawValue: 0x414)
  public static let dosPortuguese = CFString.Encoding(rawValue: 0x415)
  public static let dosIcelandic = CFString.Encoding(rawValue: 0x416)
  public static let dosHebrew = CFString.Encoding(rawValue: 0x417)
  public static let dosCanadianFrench = CFString.Encoding(rawValue: 0x418)
  public static let dosArabic = CFString.Encoding(rawValue: 0x419)
  public static let dosNordic = CFString.Encoding(rawValue: 0x41A)
  public static let dosRussian = CFString.Encoding(rawValue: 0x41B)
  public static let dosGreek2 = CFString.Encoding(rawValue: 0x41C)
  public static let dosThai = CFString.Encoding(rawValue: 0x41D)
  public static let dosJapanese = CFString.Encoding(rawValue: 0x420)
  public static let dosChineseSimplif = CFString.Encoding(rawValue: 0x421)
  public static let dosKorean = CFString.Encoding(rawValue: 0x422)
  public static let dosChineseTrad = CFString.Encoding(rawValue: 0x423)
  public static let windowsLatin2 = CFString.Encoding(rawValue: 0x501)
  public static let windowsCyrillic = CFString.Encoding(rawValue: 0x502)
  public static let windowsGreek = CFString.Encoding(rawValue: 0x503)
  public static let windowsLatin5 = CFString.Encoding(rawValue: 0x504)
  public static let windowsHebrew = CFString.Encoding(rawValue: 0x505)
  public static let windowsArabic = CFString.Encoding(rawValue: 0x506)
  public static let windowsBalticRim = CFString.Encoding(rawValue: 0x507)
  public static let windowsVietnamese = CFString.Encoding(rawValue: 0x508)
  public static let windowsKoreanJohab = CFString.Encoding(rawValue: 0x510)
  public static let ansel = CFString.Encoding(rawValue: 0x601)
  public static let jisX020176 = CFString.Encoding(rawValue: 0x620)
  public static let jisX020883 = CFString.Encoding(rawValue: 0x621)
  public static let jisX020890 = CFString.Encoding(rawValue: 0x622)
  public static let jisX021290 = CFString.Encoding(rawValue: 0x623)
  public static let jisC622678 = CFString.Encoding(rawValue: 0x624)
  public static let shiftJISX0213 = CFString.Encoding(rawValue: 0x628)
  public static let shiftJISX021300 = CFString.Encoding(rawValue: 0x628)
  public static let shiftJISX0213MenKuTen = CFString.Encoding(rawValue: 0x629)
  public static let gb231280 = CFString.Encoding(rawValue: 0x630)
  public static let gbk95 = CFString.Encoding(rawValue: 0x631)
  public static let gb180302000 = CFString.Encoding(rawValue: 0x632)
  public static let ksc560187 = CFString.Encoding(rawValue: 0x640)
  public static let ksc560192Johab = CFString.Encoding(rawValue: 0x641)
  public static let cns1164392P1 = CFString.Encoding(rawValue: 0x651)
  public static let cns1164392P2 = CFString.Encoding(rawValue: 0x652)
  public static let cns1164392P3 = CFString.Encoding(rawValue: 0x653)
  public static let iso2022JP = CFString.Encoding(rawValue: 0x820)
  public static let iso2022JP2 = CFString.Encoding(rawValue: 0x821)
  public static let iso2022JP1 = CFString.Encoding(rawValue: 0x822)
  public static let iso2022JP3 = CFString.Encoding(rawValue: 0x823)
  public static let iso2022CN = CFString.Encoding(rawValue: 0x830)
  public static let iso2022CNEXT = CFString.Encoding(rawValue: 0x831)
  public static let iso2022KR = CFString.Encoding(rawValue: 0x840)
  public static let eucJP = CFString.Encoding(rawValue: 0x920)
  public static let eucCN = CFString.Encoding(rawValue: 0x930)
  public static let eucTW = CFString.Encoding(rawValue: 0x931)
  public static let eucKR = CFString.Encoding(rawValue: 0x940)
  public static let shiftJIS = CFString.Encoding(rawValue: 0xA01)
  public static let koi8R = CFString.Encoding(rawValue: 0xA02)
  public static let big5 = CFString.Encoding(rawValue: 0xA03)
  public static let macRomanLatin1 = CFString.Encoding(rawValue: 0xA04)
  public static let hzGB2312 = CFString.Encoding(rawValue: 0xA05)
  public static let big5HKSCS1999 = CFString.Encoding(rawValue: 0xA06)
  public static let viscii = CFString.Encoding(rawValue: 0xA07)
  public static let koi8U = CFString.Encoding(rawValue: 0xA08)
  public static let big5E = CFString.Encoding(rawValue: 0xA09)
  public static let utf7IMAP = CFString.Encoding(rawValue: 0xA10)
  public static let nextStepJapanese = CFString.Encoding(rawValue: 0xB02)
  public static let ebcdicUS = CFString.Encoding(rawValue: 0xC01)
  public static let ebcdicCP037 = CFString.Encoding(rawValue: 0xC02)
  public static let utf7 = CFString.Encoding(rawValue: 0x4000100)
}

