#if !canImport(ObjectiveC)
import XCTest

extension CFStringEncodingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CFStringEncodingTests = [
        ("test_constants", test_constants),
        ("test_initialization", test_initialization),
    ]
}

extension CollectionCountTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CollectionCountTests = [
        ("test_array", test_array),
        ("test_string", test_string),
    ]
}

extension DataTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DataTests = [
        ("test_base32", test_base32),
        ("test_protocol", test_protocol),
        ("test_quotedPrintable", test_quotedPrintable),
        ("test_relativeIndex", test_relativeIndex),
        ("test_view", test_view),
    ]
}

extension DictionaryKeyValueParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DictionaryKeyValueParserTests = [
        ("test_parse", test_parse),
    ]
}

extension FileHandleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FileHandleTests = [
        ("test_dataOutputStream", test_dataOutputStream),
        ("test_fileHandleProtocol", test_fileHandleProtocol),
        ("test_objectIdentifier", test_objectIdentifier),
        ("test_readToByte", test_readToByte),
        ("test_warn", test_warn),
    ]
}

extension FileManagerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FileManagerTests = [
        ("test_sr12737", test_sr12737),
    ]
}

extension NumberTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NumberTests = [
        ("test_base32_float", test_base32_float),
        ("test_base32_integer", test_base32_integer),
    ]
}

extension StringCFStringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringCFStringTests = [
        ("test_conversion", test_conversion),
    ]
}

extension StringCaseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringCaseTests = [
        ("test_camelCase", test_camelCase),
        ("test_snakeCase", test_snakeCase),
    ]
}

extension StringEncodingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringEncodingTests = [
        ("test_IANACharSetName", test_IANACharSetName),
    ]
}

extension StringWidthTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringWidthTests = [
        ("test_width", test_width),
    ]
}

extension URLTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__URLTests = [
        ("test_localFiles", test_localFiles),
    ]
}

extension UUIDTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UUIDTests = [
        ("test_base32", test_base32),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CFStringEncodingTests.__allTests__CFStringEncodingTests),
        testCase(CollectionCountTests.__allTests__CollectionCountTests),
        testCase(DataTests.__allTests__DataTests),
        testCase(DictionaryKeyValueParserTests.__allTests__DictionaryKeyValueParserTests),
        testCase(FileHandleTests.__allTests__FileHandleTests),
        testCase(FileManagerTests.__allTests__FileManagerTests),
        testCase(NumberTests.__allTests__NumberTests),
        testCase(StringCFStringTests.__allTests__StringCFStringTests),
        testCase(StringCaseTests.__allTests__StringCaseTests),
        testCase(StringEncodingTests.__allTests__StringEncodingTests),
        testCase(StringWidthTests.__allTests__StringWidthTests),
        testCase(URLTests.__allTests__URLTests),
        testCase(UUIDTests.__allTests__UUIDTests),
    ]
}
#endif
