#if !canImport(ObjectiveC)
import XCTest

extension DataOutputStreamTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DataOutputStreamTests = [
        ("test_data", test_data),
        ("test_fileHandle", test_fileHandle),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DataOutputStreamTests.__allTests__DataOutputStreamTests),
    ]
}
#endif
