#if !canImport(ObjectiveC)
import XCTest

extension yExtensionsUpdaterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__yExtensionsUpdaterTests = [
        ("test_output", test_output),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(yExtensionsUpdaterTests.__allTests__yExtensionsUpdaterTests),
    ]
}
#endif
